### ISSUE TITLE
receipt command shouldn't require a private key

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland-cli#112]
**Is your feature request related to a problem? Please describe.**
`tableland receipt` shouldn't require a private key.

**Describe the solution you'd like**
Make it like `read`

**Comment by carsonfarmer** [comment]
Can we move this to @tablelandnetwork/js-tableland or go-tableland, that's where the work will have to happen. Agree though, this is a limitation, though currently the limitation is due to how go-tableland deals with computing receipts.

**Comment by joewagner** [comment]
I think the majority of the would-be work for this is removing the go-tableland requirement for chainId to come from the siwe token. Once that's done the SDK should be able to accommodate whatever API changes result.  
Moving this issue to go-tableland makes sense to me.
