### ISSUE TITLE
The CLI should have a sub-command to launch a custom (or external) console

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland-cli#120]

**Comment by carsonfarmer** [comment]
Depends on #118

**Comment by awmuncy** [comment]
Still waiting on the new D1 compatible SDK changes to land to complete, but this command is working in the shell-and-ens feature branch.

**Comment by awmuncy** [comment]
Work completed here: https://github.com/tablelandnetwork/js-tableland-cli/pull/150
