### ISSUE TITLE
Build ENS namespacing into the CLI as an experiment for this approach

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland-cli#124]
# Input for this experiment:
- Dealing with `prefix_chainID_tokenID` table names is cumbersome.
- Some kind of namespace for a _group of tables_ sounds very attractive.
- This namespacing should be resolvable on- and off-chain.
- The validator should not need to handle resolving namespace -> table mapping, as this would introduce another source of truth. 
- The validator is not a good place to _store_ the mapping, as this would make it unavailable off-chain (unless duplicated).
- Building a unique namespace management system is complex and comes with a number of important considerations:
  - Name expirations are important to ensure no permanent lock-in of a given name.
  - Interop with existing tools is important, but requires a lot of traction to make happen.
- ENS is the most widely adopted name system in the Ethereum ecosystem.
- ENS plans to launch on L2 but are currently not on any.
- Whatever we do here should be done slowly and with great consideration / testing because it would be very hard to back peddle.

# The experiment
Determine if ENS domains (top-level or subdomains) can provide a "good enough" mapping from a "name" to a set of tables. We can do this without touching the SDK... just trying to get a feel for it with as little work as possible.

Consider an app that needs tables for inventory, customers, and sales.

## Creating the tables

Assume this hypothetical user has a `.tablelandrc` file with their private key and other needed params set (chain, etc), and that they own the `foo.eth` ENS domain.

```bash
> tableland create --ns myapp.foo.eth "id integer primary key, item text, count int" inventory
Namespace 'myapp.foo.eth' not found. Would you like to create it? N/y
> y
Namespace 'myapp.foo.eth' created
Table 'inventory.myapp.foo.eth' created.
```

### What's going on here?
1. Using etherjs / ennjs, the CLI creates the subdomain `myapp` under `foo.eth`
2. CLI creates the table as usual (nothing special here)
3. Using etherjs / ennjs, the CLI set's the _content_ field of the subdomain to be a JSON key value store of prefix -> full table name, e.g., 
```JSON
{
    "inventory": "<chainID>_<tokenID>"
}
```
4. If the user didn't own `foo.eth`, the CLI _could_ ask if they want to register it and do it for them (if it's available).
5. This same flow could also work for top-level domain names, but this would mean every "namespace" is mapped 1:1 with an ENS domain, which generally be a more expensive way of managing namespace. Nevertheless, it should still be doable if somebody wants to do that.

## Create the other tables
```bash
> tableland create --ns myapp.foo.eth "id integer primary key, name text" customers
Table 'customers.myapp.foo.eth' created.

> tableland create --ns myapp.foo.eth "id integer primary key, customer_id int, inventory_id int, count int" sales
Table 'sales.myapp.foo.eth' created.
```

### What's going on here?
1. The namespace already exists, so no need to prompt about creating it.
2. The content field of `myapp.foo.eth` is now:

```JSON
{
    "inventory": "<chainID>_<tokenID>",
    "customers": "<chainID>_<tokenID>",
    "sales": "<chainID>_<tokenID>"
}
```

### From the CLI

```
> INSERT INTO inventory.myapp.foo.ens (...) VALUES (...);
{txn info}
```

#### What's going on here?
1. Using etherjs, the CLI resolves the name after pruning the first part of the "namespace", ie, `myapp.foo.ens` and reads it's content, which is our JSON mapping
2. The CLI then finds the _real_ table name that is being touched and proceeds as normal.

### From solidity
It's possible to [resolve an ENS domain on-chain](https://docs.ens.domains/contract-developer-guide/resolving-names-on-chain), but I haven't looked into whether or not you can extract the content field. If you can, then this works in much the same way as from the CLI. We could have some helper methods to that do the resolving under the hood.

## Reading from the tables in the namespace

```
> SELECT * from customers.myapp.foo.ens;
{rows}
```

### What's going on here?
1. Using etherjs, the CLI resolves the name after pruning the first part of the "namespace", ie, `myapp.foo.ens` and reads it's content, which is our JSON mapping
2. The CLI then finds the _real_ table name that is being touched and proceeds as normal.

## Downsides
1. This approach handles the namepacing at the client layer, meaning that queries in URLs that hit a gateway can't have namespace references. Unless we want to get ENS resolving into the gateway, which may not be a bad idea.

## Other considerations
1. This approach could be extended to support other popular name services like Unstoppable Domains

**Comment by andrewxhill** [comment]
here's a pretty good and simple ens schema example that arose from playing with it quite a bit this weekend.

https://app.ens.domains/name/tictactoe.rockefeller.eth/details

`tictactoe.rockefeller.eth` has 3 text fields

```
xyz.tableland.players: temp1_80001_541
xyz.tableland.results: temp1_80001_540
xyz.tableland.disputes: events_80001_436
```

so, when connected to this ens, just use players, results, and disputes for short names for the tables. matching the json setup more or less. 

the key bits:

1. works the same as above but follows the patterns of the text record name space. for example, com.reddit in the defaults. 
2. this is fully readable on chain since you know every key will map to a single string. versus parsing an arbitrary json payload, which would be really hairy. just look for any keys that start with`xyz.tableland` and you're in business. 
3. use subdomains as the namespace since they work really well for that. it also means you can use all the other fields to document your app metadata when helpful. 
4. no other tools that support ens things need to know something about our json payloads.

**Comment by sanderpick** [comment]
super, very cool that text fields can be arbitrary. nice exploration! sounds promising.
