### ISSUE TITLE
Provide support for specifying a custom baseUrl from the CLI

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland-cli#152]
**Is your feature request related to a problem? Please describe.**
Currently the CLI does not allow one to specify a custom baseUrl (new name) via flags or a config. But the SDK does. It would be useful to be able to specify this from the CLI as well.

**Describe the solution you'd like**
Add the flag, use it in the CLI, and provide a default when not specified.

**Describe alternatives you've considered**
Not doing this is how it is now, and I'd like to see this possibility.

**Additional context**
This is also a feature request from a user via Discord.

**Comment by awmuncy** [comment]
Seems pretty straightforward. In the SDK, the static `readOnly` method to create a readonly Database only takes the `chain` argument instead of an options argument. So for a Database with a signer I can also specify a baseurl, but not for a readonly database.

**Comment by carsonfarmer** [comment]
Sure you can. Just do:

```
const db = new Database({ baseUrl }) // Readonly Database
```

**Comment by awmuncy** [comment]
Ah, not sure why I thought it required a signer. 🤦 Ty.

**Comment by dtbuchholz** [comment]
I received some user feedback that being able to specify a custom gateway would be useful. The team is running their own Tableland validator and using the CLI, so they want to be able to read from their own node.
