### ISSUE TITLE
--chain flag is ignored when creating tables

### ISSUE THREAD

**Issue by asutula** [tablelandnetwork/js-tableland-cli#187]
**Describe the bug**
I'm setting the `--chain` flag to `local-tableland` when creating a table, and the resulting table is created on Goerli. Which is weird because that is apparently not the default chain.

**To Reproduce**

```
tableland --chain=local-tableland create 'k text, v text' --prefix=foo
{
  meta: {
    duration: 24183.75741699338,
    txn: {
      tableId: '1392',
      transactionHash: '0xad57b4e6ba8495ac16ae780c2e69c0ab713088a7ec5ff693fb0936daf4e2c4e2',
      blockNumber: 8422502,
      chainId: 5,
      wait: [AsyncFunction: wait],
      name: 'foo_5_1392',
      prefix: 'foo'
    }
  },
  success: true,
  results: [],
  link: ''
}
```

**Expected behavior**
A table should be created on local tableland

**Screenshots**

**Desktop (please complete the following information):**

- OS: MacOS 13.2

**Additional context**
```
> tableland --version
4.0.1-rc1.0
```

**Comment by awmuncy** [comment]
Do you have a .tablelandrc file? And if so, is it's "providerUrl" pointing to a goerli provider?

**Comment by asutula** [comment]
Yes, that was it. Sounds like this isn't so much a bug, but something that can be improved by checking that rc file values don't conflict with flags.

**Comment by joewagner** [comment]
https://github.com/tablelandnetwork/local-tableland is overriding config files with command flags, this is my intuition for command line tools, but it doesn't have to be this way.  
Should we decide on one way to setting this up for all of our tools?
