### ISSUE TITLE
Feature: Add ability to transfer table

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland-cli#20]
capturing here, but of course would require a new method in the SDK for this to work here.

**Comment by joewagner** [comment]
This will be a very quick change to the SDK, I'm happy to do that.

**Comment by carsonfarmer** [comment]
Do we have an issue or TPD for the SDK for this work yet?

**Comment by sanderpick** [comment]
I figured this issue was enough since transfer is a basic feature of the registry, and the SDK should support those basic functions. Transfer is how you change ownership.
