### ISSUE TITLE
NPM "latest" tag is old release

### ISSUE THREAD

**Issue by asutula** [tablelandnetwork/js-tableland-cli#200]
This results in version 3.x being installed when simply running `npm install -g @tableland/cli`. I had to explicitly install version `4.0.2` to get the latest.

**Comment by joewagner** [comment]
I think the publish workflow should be adding the latest tag for us.  Maybe this package was published to npm manually?

**Comment by carsonfarmer** [comment]
Yeh weird, the workflow should be doing that for us? But I know there was a bug in the workflow at one point, maybe it didn't get fixed? @awmuncy did you publish that one manually, or use the publish workflow?

**Comment by awmuncy** [comment]
No bug here. I had published through the workflow, but due to a couple bugs, I manually set it to 3.1.2, thinking I'd keep it there until the official SDK 4.x was released. I see that was released last night, so I'll point to 4.x on the CLI now.

**Comment by asutula** [comment]
Thanks everyone.
