### ISSUE TITLE
When JSON objects are returned as query result, they are not displayed

### ISSUE THREAD

**Issue by asutula** [tablelandnetwork/js-tableland-cli#201]
It just prints out:

```
[Object]
```

I'm using version 4.0.2. The full output looks like:

```
{
  meta: { duration: 482.26458287239075 },
  success: true,
  results: [
    {
      "my_result": [Object]
    }
  ]
}
```

**Comment by joewagner** [comment]
Looks like we need to be using `console.log(JSON.stringify(dataOrWhatever))` instead of `console.log(dataOrWhatever)`.
I wonder if there's a way to write a test that ensures this behavior?

**Comment by carsonfarmer** [comment]
We _had_ tests for this exactly... not sure what's up there? I think maybe some changes recently from @awmuncy's work? Either way, for anything that _can_ be JSON output, we should probably use console.dir or the above JSON stringify process right?

**Comment by carsonfarmer** [comment]
Hey @awmuncy we should make sure we put back those tests that actually test the _output_ string, not just the object itself please.

**Comment by carsonfarmer** [comment]
that's how we used to do it, but @awmuncy didn't like that it was a string and not a colored object. does JSON.stringify allow you to colorize output? or provide a function that does?

**Comment by joewagner** [comment]
You can try to use the second arg to json.stringify.  Alternatively, mayb there's an existing package that has solved this kind of thing?

**Comment by awmuncy** [comment]
I think `console.dir(object, {depth: null});` will allow for infinite depth and colorization (at least in Bash). I only added dir to one or two commands, since the rest didn't result in depth that resulted in the [Object] problem. But we didn't test for when rows from the table were JSON. I just switched so the rest of the commands use dir as well, and it seems to work. 

On that note, we never tested queries which resulted in a JSON response. @joewagner could we add by default a table in local-tableland that has JSON in one of it's columns?

**Comment by carsonfarmer** [comment]
Wait, why not just create the table in the tests?

**Comment by awmuncy** [comment]
It's possible to configure the test setup in this repository to create the table with JSON results. But it's worth considering that other projects with a local-tableland dependency may also benefit from this approach, so we could also do it there.

**Comment by carsonfarmer** [comment]
Hmmm, I buy that this could be useful for testing and demos probably even more usefully. But in that case, we might want to think about a whole suite of tables with various features that help showcase Tableland capabilities (JSON, JOINs, etc). I'll create a ticket for that in local-tableland.

**Comment by carsonfarmer** [comment]
Never mind, I this has already been discussed: https://github.com/tablelandnetwork/local-tableland/issues/106

**Comment by awmuncy** [comment]
https://github.com/tablelandnetwork/js-tableland-cli/pull/202
