### ISSUE TITLE
Do manual QA testing of CLI using protocol version that does not include the possibility of relays or RPC

### ISSUE THREAD

**Issue by joewagner** [tablelandnetwork/js-tableland-cli#203]

**Comment by awmuncy** [comment]
The 4.x CLI relies entirely on the 4.x SDK to interface with the protocol, which uses the new API, which doesn't support relays. This this is just... manually testing the existing CLI?

**Comment by joewagner** [comment]
> The 4.x CLI relies entirely on the 4.x SDK to interface with the protocol, which uses the new API, which doesn't support relays. This this is just... manually testing the existing CLI?

Yeah, the cli should be all ready setup to work once the validator drops the lagacy api.  I mostly made this as a reminder to do a double check before we fully deploy the validator without the legacy stuff.
