### ISSUE TITLE
Table `create` uses `undefined` if no prefix provided

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland-cli#209]
**Describe the bug**
I've created a table using the CLI on `local-tableland` and don't pass a prefix. It creates a table with prefix `undefined` instead of an empty string.

**To Reproduce**
Create a table: `tableland create "id int primary key, name text"`

See the response with name `undefined_31337_2`:
```
{
  meta: {
    duration: 143.90570831298828,
    txn: {
      tableId: '2',
      transactionHash: '0xcb227f1fa1fba4e53b194c703c6230c0b0e87c1c7e187c520547137e247d3a2e',
      blockNumber: 240,
      chainId: 31337,
      wait: [AsyncFunction: wait],
      name: 'undefined_31337_2',
      prefix: 'undefined'
    }
  },
  success: true,
  results: [],
  link: ''
}
```
**Desktop (please complete the following information):**

- CLI: 4.0.3
- Node: v18

**Comment by awmuncy** [comment]
Resolved in #208.
