### ISSUE TITLE
Duplicate values returned in shell respone

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland-cli#210]
**Describe the bug**
I'm using the `shell` command. When I run something like `tableland read <statement>`, the response has duplicate values returned.

**To Reproduce**
Create a table, insert values into, and then open the shell with `tableland shell` to read data:
```
tableland> select * from cli_demo_table_31337_2;
```
The response has duplicate values returned:
```
{
  meta: { duration: 18.574082374572754 },
  success: true,
  results: [ { id: 1, name: 'Bobby Tables' } ]
}
{
  response: {
    meta: { duration: 18.574082374572754 },
    success: true,
    results: [ { id: 1, name: 'Bobby Tables' } ]
  }
}
```

**Expected behavior**
Only one value should be returned, but a second object with key `response` is duplicative.

**Desktop (please complete the following information):**

- Version: 4.0.3

**Comment by awmuncy** [comment]
Resolved in #208
