### ISSUE TITLE
receipt command is broken, returns ethers error "could not detect network" NETWORK_ERROR

### ISSUE THREAD

**Issue by datadanne** [tablelandnetwork/js-tableland-cli#213]
The `receipt` command doesn't work. I've tried both with mumbai transactions and mainnet transactions and both are broken. 
```
$ tableland version
4.0.4
```
Example receipt command that doesn't work
```
$ tableland receipt 0xe2c275e1d9bb83443e9046bf322efbd19e1fac70a26ed565f7449c9b9f4284be --chain mainnet --k 0x00000000000000000000000000000000000000000000000000000000deadbeef
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
```

**Comment by joewagner** [comment]
Looks like the default provider is not being used, and the only way to get receipt to work is by passing in a `providerUrl` flag.
I have a fix PR incoming.
