### ISSUE TITLE
[JSTC-22] Update README

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland-cli#295]
**About:** 

Tableland CLI - A developer tool for creating, editing, and querying tables in Tableland's permissionless database. 

**Intro:** 

The Tableland CLI is a developer tool designed to simplify connecting to supported blockchains, creating, writing to, and reading from tables, and managing table permissions, all from your command line.

<sub>From [SyncLinear.com](https://synclinear.com) | [JSTC-22](https://linear.app/tableland/issue/JSTC-22/update-readme)</sub>

**Comment by daredevil3435** [comment]
I would like to contribute to this issue, how do I get started?
