### ISSUE TITLE
[JSTC-23] Update maticmum in the default chains (and maybe other views)

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/js-tableland-cli#299]
When running `tableland init` you see a list of options for default chain. `maticmum` should just be matic-mumbai to follow the pattern like arbitrum-goerli 

<sub>From [SyncLinear.com](https://synclinear.com) | [JSTC-23](https://linear.app/tableland/issue/JSTC-23/update-maticmum-in-the-default-chains-and-maybe-other-views)</sub>

**Comment by joewagner** [comment]
We used to call Polygon Mumbai `polygon-mumbai` but we switched to match ethers.js (and maybe chainlist?)
Here is the issue where we switched from a custom naming scheme to the current scheme: https://github.com/tablelandnetwork/evm-tableland/issues/237
It adds some friction to have to map names between ethers and our networks, maybe we can add something to the docs that lists the network names? My sense is that devs are familiar with our current standard, but maybe the list that comes up for init could be a human readable?
cc: @carsonfarmer

**Comment by andrewxhill** [comment]
also just spotted that the `SDK Network Name` field here is backwards for the two polygon nets here: https://docs.tableland.xyz/fundamentals/chains/polygon#polygon-mumbai-testnet @dtbuchholz
