### ISSUE TITLE
[JSTC-24] Command `tableland chains` needs a flag for human readable

### ISSUE THREAD

**Issue by andrewxhill** [tablelandnetwork/js-tableland-cli#300]
right now it's just the full json dump of all chain info. looks really handy for chaining w/ jq or something, but not super useful when trying to grab a chain id or name. 

<sub>From [SyncLinear.com](https://synclinear.com) | [JSTC-24](https://linear.app/tableland/issue/JSTC-24/command-tableland-chains-needs-a-flag-for-human-readable)</sub>

**Comment by joewagner** [comment]
How about using `--pretty`?

**Comment by joewagner** [comment]
We could also use `--verbose`?

**Comment by sanderpick** [comment]
> How about using `--pretty`?

that sounds good to me. ie, use a table style like we do for reads w/ --pretty

**Comment by joewagner** [comment]
Fixed by #302
