### ISSUE TITLE
[JSTC-29] Enable support for INSERT + GROUP BY subqueries

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland-cli#317]
With updates to the parser ([GSP-14](https://linear.app/tableland/issue/GSP-14/add-group-by-support-for-insert-subqueries) / [wasm PR](https://github.com/tablelandnetwork/wasm-sqlparser/pull/208)), the CLI should make sure that it supports INSERT + GROUP BY subqueries. At a minimum, this means bumping the `@tableland/sqlparser` dep version *plus* the SDK (once it does the same), but in case there are any tests etc. that touch on this previously disabled feature, these have to be updated as well.

<sub>From [SyncLinear.com](https://synclinear.com) | [JSTC-29](https://linear.app/tableland/issue/JSTC-29/enable-support-for-insert-group-by-subqueries)</sub>

**Comment by joewagner** [comment]
This is fixed by https://github.com/tablelandnetwork/js-tableland-cli/pull/332
