### ISSUE TITLE
[JSTC-18] Provide (standard) way for users to specify schemas (and share them) for table creation

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland-cli#73]
**Is your feature request related to a problem? Please describe.**

- Currently it is difficult to share schemas among projects. It would be really useful to find a standardized way to share these, and to then support this format for create statements
- Creating tables currently feels less SQL-ish than we'd like. Perhaps there are standards we can use to make this less ad hoc

**Describe the solution you'd like**

Some sort of standardized schema representation format that we can use on Tableland

**Describe alternatives you've considered**

Dune uses something like this: https://github.com/duneanalytics/spellbook/blob/tokens-unique-test/models/nft/ethereum/nft_ethereum_schema.yml, but this is really for "models" or "views" rather than table schemas per se.

**Additional context**

This would make sharing and creating tables from the CLI for lager projects much more doable. It would also benefit from some of the planned work around local config files.

<sub>[JSTC-18](https://linear.app/tableland/issue/JSTC-18/provide-standard-way-for-users-to-specify-schemas-and-share-them-for)</sub>

**Comment by carsonfarmer** [comment]
This might actually be related to work you're doing, right @asutula?

**Comment by asutula** [comment]
Possibly. I'm just letting people specify the schema string in a config file. I suppose those configurations could be shared, but I also wonder what the best way of defining a schema is. Is more-sql-ish better or worse? Is something more model/orm-like better? I don't know.

**Comment by carsonfarmer** [comment]
yeh defs a good question. to be honest, I think something more sql-ish is the right path from tableland perspective. high-level tools can be built on top of that. for instance, sqlite just encodes the entire create statement as the schema definition. nothing more, nothing less.
