### ISSUE TITLE
Feature: Validate and normalize SQL statements

### ISSUE THREAD

**Issue by carsonfarmer** [tablelandnetwork/js-tableland-cli#85]
Currently, the wasm-sqlparser library is a standalone library without any easy or direct way for users to test and normalize sql statements outside of using a demo web app or the admin panel. It would be a really great first step towards providing better was for devs to validate sql statements (at least in terms of the tableland parser) if we integrated the sql parser into the cli.

**Comment by carsonfarmer** [comment]
I'm planning the implementation of this functionality for release _before_ the end of this season. Currently, I'm thinking an API like this feels useful. I'm curious if you have some thoughts here @sanderpick and/or @asutula (keep in mind that the query API itself might change in the near future, but that this is how things work now):

```
tableland query "select * from some_table_5_99 where oops!" --normalize
```

This additional `normalize` flag would essentially run the above through our parser before trying to submit the query to the network, thereby potentially catching a SQL bug before trying to send it. The same flag could be used to even greater effect on write and create statements.

In addition to the above, a standalone normalize statement could be added, which would simply take an input stream (or stdin) and output normalized SQL to stdout, or print an error to stderr.

```
tableland normalize "some sql"
```

or something like:

```
echo "select * from table_5_00" | tableland normalize | tableland query | jq
```

**Comment by sanderpick** [comment]
could we normalize by default?

**Comment by carsonfarmer** [comment]
Yeh why not? it's pretty cheap!

In the end, this is actually _not_ going to matter much anymore because I think we'll likely (depending on next week's convos) move away from a read, write, create API to a single exec style API, in which case, we'll _always_ have to normalize everything anyway.

**Comment by carsonfarmer** [comment]
Yes, that is the way we went with this. So now, everything is normalized within the SDK... so we don't really have to handle it here at all.
