### ISSUE TITLE
Release CLI with Arbitrum support

### ISSUE THREAD

**Issue by sanderpick** [tablelandnetwork/js-tableland-cli#89]

**Comment by sanderpick** [comment]
@carsonfarmer @joewagner and this one here

**Comment by joewagner** [comment]
Fixed by https://github.com/tablelandnetwork/js-tableland/commit/15ccd2b8ec13d6e4f329497cd68fc4578874890f

**Comment by carsonfarmer** [comment]
Wait, this is only actually "fixed" once we actually upgrade to the next release of js-tableland.

**Comment by carsonfarmer** [comment]
Hmmm, not quite sure actually.

**Comment by joewagner** [comment]
> Hmmm, not quite sure actually.

Looking at this more, I don't quite know why, but it looks like dependabot will only open a max of 5 prs at a time.  If we `combinepr` and merge the open ones here, I think it will pickup the sdk updates.
