### ISSUE TITLE
Remove double quotes around `token` command's returned SIWE token

### ISSUE THREAD

**Issue by dtbuchholz** [tablelandnetwork/js-tableland-cli#9]
### User Story:
I am creating an env var `TBL_TOKEN`, which uses the value returned from the `token` command. This value is the SIWE token, a continuous string of characters inside double quotes (`"asdf..."`). When piping the output of `tableland token` into a new env variable, I have to parse the response to retrieve the SIWE token inside of these double quotes. If I do not parse this token string and/or remove the double quotes, I run into issues when trying to use `TBL_TOKEN` across any other commands. Namely, I must do something like `export TBL_TOKEN=$(tableland token | cut -d '"' -f2)` instead of simply `export TBL_TOKEN=$(tableland token)`

### Steps to Reproduce
1. Run the command `export TBL_TOKEN="$(tableland token)"`
2. Try to run `tableland create` or `tableland write` (fails)
3. Run `unset TBL_TOKEN` and then run `export TBL_TOKEN="$(tableland token | cut -d '"' -f2)"`
4. Try to run `tableland create` or `tableland write` (succeeds)
At step 2, an error is thrown:
```
Error: Bad Request
    at /usr/local/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/cjs/lib/tableland-calls.js:37:19
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/cjs/lib/tableland-calls.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/cjs/lib/tableland-calls.js:4:12)
    at parseResponse (/usr/local/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/cjs/lib/tableland-calls.js:35:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/cjs/lib/tableland-calls.js:30:16)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/cjs/lib/tableland-calls.js:5:58)
```

**Comment by dtbuchholz** [comment]
Note: could be nativity on best practices for setting up env vars, but I _think_ this is a better way to do things?

**Comment by carsonfarmer** [comment]
Where did we land on this once @dtbuchholz? Do we still want the CLI output to drop the quotes? The thing that makes me hesitate, is that all response from the CLI are valid JSON. But a single "string" without quotes _isn't_ valid JSON. That makes passing the response to tools like `jq` et al harder... thoughts?

**Comment by dtbuchholz** [comment]
@carsonfarmer it's probably fine as-is and no need to drop it due to your rationale. The docs at least mentioned the "cut" command / how-to extract the string, so I don't see this as an issue. Can close it out.

**Comment by carsonfarmer** [comment]
Closing this as "won't fix" for the reasons provided.
